export const TopicList = [
  'Summarize Think and Grow Rich',
  'Create a simple html page',
  'Create a html vat calculator',
  'Create a javascript countdown to December 31st 2023',
  'Create a PHP mortgage calculator',
  'Create a function in C++',
  'fix this code (paste your code)',
  'Improve this headline (add your headline)',
  'Write a slogan for a coffee bean company',
  'Write a letter demanding my landlord address a mould and damp issue in the home I rent',
  'Create a 6 month employment contract for a freelance graphic designer',
  'How do I grow a YouTube channel?',
  'How do I grow a brand on Amazon FBA?',
  'Write a short story about a cat named Mimi',
  'Create a 2000 calorie 7-day meal plan',
  'Update it with these macros: protein 35% and carbs 55%',
  'Now make it vegetarian',
  'Write a wedding speech for a groom named Brian who is marrying Jenny',
  'Write an email inviting people to my wedding',
  'Write a cold email to a dog grooming business to sell them SEO services',
  'Now turn it into a text',
  'Write 5 titles for a blog-post about learning to use AI',
  'Write an outline for the article using title 3',
  'Write the introduction',
  'Create 5 google ads to promote a pet grooming business',
  'Write a song about a dog that turns to crime to feed it’s bone addiction (THIS ONE IS HILARIOUS)',
  'Output the first page of Alice in Wonderland',
  'Translate it into Spanish',
  'Create a YouTube video script for a review about chat GPT',
  'Teach me how to use Photoshop',
  'Now teach me how to create a motion blur',
  'Come up with a few name ideas for a cat using wordplay',
  'Create a Chrome extension to print a page to PDF',
  'Suggest 10 birthday gifts for a 40 year old man',
  "pretend you're a create-your-own-adventure video game. Set the scene and give me 4 choices to proceed to the next stage.",
  'List what items I need to go on a trip on the London to Amsterdam train',
  'Give me a recipe for Spanish omelette',
  'Write a job application to Open AI',
  'Update it with the following: I have a BSC in computing from the university of Sesame Street',
  'Write the script for the next Hollywood blockbuster',
  'Adapt it for Bollywood',
  'List 10 ideas for a million dollar product in 2023',
  'Tell me an extremely funny joke that involves 3 characters',
  'Can you provide me with some ideas for blog posts about [topic of your choice]?',
  'Write a minute-long script for an advertisement about [product or service or company]',
  'Write a product description for my [product or service or company]',
  'Suggest inexpensive ways I can promote my [company] with/without using [Media channel]',
  'How can I obtain high-quality backlinks to raise the SEO of [Website name]',
  'Make 5 distinct CTA messages and buttons for [Your product]',
  'Create a [social media] campaign plan for launching an [your product], aimed at [ Your target audience]',
  'Analyze these below metrics to improve email open rates for a fashion brand <paste metrics>',
  'Write follow-up emails to people who attended my [webinar topic] webinar',
  'Structure a weekly [newsletter topic] newsletter',
  'Make a post showcasing the benefits of using our product [product name] for [specific problem/issue].',
  'Generate 5 creative ways to use Instagram Reels for [your product or service or company]',
  'Create a social media post that targets [the specific audience] and explains how our product [product name] can help them.',
  'Create a personalized email greeting for a VIP customer',
  'Write a list of 5 YouTube video ideas for [your product or company]',
  'Create two Google Ads in an RSA format (using multiple headlines and descriptions) for an A/B test for “Your product”.',
  'Write a 100-character meta description for my blog post about <topic>.',
  'Create a magical system that emphasizes education and is based on [topic of your choice].',
  'Teach me the <topic of your choice> and give me a quiz at the end, but don’t give me the answers and then tell me if I answered correctly.',
  'Describe <topic of your choice> in detail.',
  'Create a YAML template to detect the Magento version for the Nuclei vulnerability scanner.',
  'Can you provide a summary of a specific historical event?',
  'Can you give me an example of how to solve a [Problem statement]?',
  'Write a paper outlining the topic [Topic of your choice] in chronological order.',
  'I need help understanding how probability works.',
  'I need help uncovering facts about the early 20th-century labor strikes in London.',
  'I need help providing an in-depth reading for a client interested in career development based on their birth chart.',
  'Please provide a definition for the medical term ‘tachycardia’.',
  'Come up with 10 ways to improve memory and recall while studying for exams.',
  'Suggest 10 Chrome extensions for students designed to improve productivity while studying.'
]
