export const TopicList = [
  'Summarize Think and Grow Rich',
  'Create a simple html page',
  'Create a html vat calculator',
  'Create a javascript countdown to December 31st 2023',
  'Create a PHP mortgage calculator',
  'Create a function in C++',
  'fix this code (paste your code)',
  'Improve this headline (add your headline)',
  'Write a slogan for a coffee bean company',
  'Write a letter demanding my landlord address a mould and damp issue in the home I rent',
  'Create a 6 month employment contract for a freelance graphic designer',
  'How do I grow a YouTube channel?',
  'How do I grow a brand on Amazon FBA?',
  'Write a short story about a cat named Mimi',
  'Create a 2000 calorie 7-day meal plan',
  'Update it with these macros: protein 35% and carbs 55%',
  'Now make it vegetarian',
  'Write a wedding speech for a groom named Brian who is marrying Jenny',
  'Write an email inviting people to my wedding',
  'Write a cold email to a dog grooming business to sell them SEO services',
  'Now turn it into a text',
  'Write 5 titles for a blog-post about learning to use AI',
  'Write an outline for the article using title 3',
  'Write the introduction',
  'Create 5 google ads to promote a pet grooming business',
  'Write a song about a dog that turns to crime to feed it’s bone addiction (THIS ONE IS HILARIOUS)',
  'Output the first page of Alice in Wonderland',
  'Translate it into Spanish',
  'Create a YouTube video script for a review about chat GPT',
  'Teach me how to use Photoshop',
  'Now teach me how to create a motion blur',
  'Come up with a few name ideas for a cat using wordplay',
  'Create a Chrome extension to print a page to PDF',
  'Suggest 10 birthday gifts for a 40 year old man',
  "pretend you're a create-your-own-adventure video game. Set the scene and give me 4 choices to proceed to the next stage.",
  'List what items I need to go on a trip on the London to Amsterdam train',
  'Give me a recipe for Spanish omelette',
  'Write a job application to Open AI',
  'Update it with the following: I have a BSC in computing from the university of Sesame Street',
  'Write the script for the next Hollywood blockbuster',
  'Adapt it for Bollywood',
  'List 10 ideas for a million dollar product in 2023',
  'Tell me an extremely funny joke that involves 3 characters'
]
